c_in: 1025
s_c_h: 128
d_c_h: 128
c_bank: 128
c_latent: 128
c_cond: 128
kernel_size: 7
bank_size: 8 
bank_scale: 1
s_enc_n_conv_blocks: 6
s_enc_n_dense_blocks: 2
d_enc_n_conv_blocks: 6
d_enc_n_dense_blocks: 0
s_subsample: [1, 1, 2, 1, 1, 2]
d_subsample: [1, 1, 2, 1, 1, 2]
dec_n_conv_blocks: 6
dec_n_dense_blocks: 2
dec_n_mlp_blocks: 4
upsample: [2, 1, 1, 2, 1, 1] 
act: 'lrelu'
dropout_rate: 0.5
dis_c_h: 128
dis_kernel_size: 5
dis_n_conv_blocks: 5
dis_subsample: [1, 2, 1, 2, 1]
dis_n_dense_layers: 5
dis_d_h: 1024
segment_size: 32
frame_size: 1
batch_size: 8
shuffle: True
gen_lr: 0.0001
dis_lr: 0.0002
beta1: 0.5
beta2: 0.9
amsgrad: False
init_lambda_rec: 10
final_lambda_rec: 10
lambda_srec: 1
lambda_dis: 1
lambda_kl: 0.01
lambda_gp: 10
weight_decay: 0.0001
add_gaussian: False
gaussian_std: 0.1
grad_norm: 1
ae_steps: 1
dis_steps: 1
dis_sched_iters: 10000
rec_sched_iters: 30000
sample_rate: 22050
sn: False
use_dummy: True
use_mismatch: False
